version: '3'

services:
  frontend:
    build: frontend
    ports:
      - 3000:3000
    environment:
      NEXT_PUBLIC_API_ENDPOINT: 'http://localhost:8000'
    volumes: []

  backend:
    build: backend
    ports:
      - 8000:8000
    environment:
      RUST_LOG: info
    volumes:
      - ./posts:/app/posts
