name: Build, Lint, Type check and Test

on:
  push:
    branches: [main]
    paths:
      - 'frontend/**'
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ^14.18.1
          path: ./frontend
      - id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
        with:
          path: ./frontend
      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - run: yarn
        with:
          path: ./frontend
      - run: yarn build
        with:
          path: ./frontend

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ^14.18.1
          path: ./frontend

      - id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
        with:
          path: ./frontend
      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - run: yarn
        with:
          path: ./frontend
      - run: yarn format
        with:
          path: ./frontend
      - run: yarn lint
        with:
          path: ./frontend

  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ^14.18.1
          path: ./frontend

      - id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
        with:
          path: ./frontend
      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - run: yarn
        with:
          path: ./frontend
      - run: yarn type-check
        with:
          path: ./frontend

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ^14.18.1
          path: ./frontend

      - id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
        with:
          path: ./frontend
      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - run: yarn
        with:
          path: ./frontend
      - run: yarn test
        with:
          path: ./frontend
